# Generated by Django 3.1.7 on 2021-05-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
