# Generated by Django 3.1.7 on 2021-05-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_userprofile_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ip',
            new_name='address',
        ),
    ]
